INFO: Log file created: D:\2025\Projects\Presence\Presence0.1\Uploader\Logs\20250306_020125.log


INFO: Channel provided from command line: God Mode Notes
INFO: Earliest folder found: D:\2025\Projects\Presence\Presence0.1\Channels\God Mode Notes\Clips\20250304_210014

INFO: YouTube AutoUpload for channel: 'God Mode Notes', folder: 'D:\2025\Projects\Presence\Presence0.1\Channels\God Mode Notes\Clips\20250304_210014'
ERROR: 'AutoUploadYouTube.py' failed with exit code 1
INFO: Video file: D:\2025\Projects\Presence\Presence0.1\Channels\God Mode Notes\Clips\20250304_210014\20250304_210014.mp4 (Timestamp: 20250304_210014)
Traceback (most recent call last):
  File "D:\2025\Projects\Presence\Presence0.1\Uploader\Youtube\AutoUpload - Youtube\Code\AutoUploadYouTube.py", line 261, in <module>
    main()
  File "D:\2025\Projects\Presence\Presence0.1\Uploader\Youtube\AutoUpload - Youtube\Code\AutoUploadYouTube.py", line 252, in main
    bot = start_browser()
          ^^^^^^^^^^^^^^^
  File "D:\2025\Projects\Presence\Presence0.1\Uploader\Youtube\AutoUpload - Youtube\Code\AutoUploadYouTube.py", line 61, in start_browser
    return webdriver.Chrome(service=service, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\omers\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\omers\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\omers\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "C:\Users\omers\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\omers\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\omers\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 133
Current browser version is 135.0.7049.3 with binary path C:\Program Files\Google\Chrome Beta\Application\chrome.exe
Stacktrace:
	GetHandleVerifier [0x00007FF71CE5B405+3109445]
	(No symbol) [0x00007FF71CADB190]
	(No symbol) [0x00007FF71C978FDA]
	(No symbol) [0x00007FF71C9BCE2B]
	(No symbol) [0x00007FF71C9BBE6B]
	(No symbol) [0x00007FF71C9B6306]
	(No symbol) [0x00007FF71C9B1596]
	(No symbol) [0x00007FF71CA0545B]
	(No symbol) [0x00007FF71CA04A30]
	(No symbol) [0x00007FF71C9F7013]
	(No symbol) [0x00007FF71C9BFF5E]
	(No symbol) [0x00007FF71C9C11E3]
	GetHandleVerifier [0x00007FF71CEBB41D+3502685]
	GetHandleVerifier [0x00007FF71CED6993+3614675]
	GetHandleVerifier [0x00007FF71CECBD23+3570531]
	GetHandleVerifier [0x00007FF71CC2ECBA+830202]
	(No symbol) [0x00007FF71CAE643F]
	(No symbol) [0x00007FF71CAE2294]
	(No symbol) [0x00007FF71CAE2436]
	(No symbol) [0x00007FF71CAD1E89]
	BaseThreadInitThunk [0x00007FFC087B259D+29]
	RtlUserThreadStart [0x00007FFC09BAAF38+40]


